---
- name: Run the runBenchmarkTest_Perf_Producer.sh to perform benchmarking.
  command: "{{ jmeter_remote_bin_dir_full_path }}/runBenchmarkTest_Perf_Producer.sh"
  register: runBenchmarkTest_Perf_Producer_console_output

- name: Print benchmark results to console
  debug:
    msg: "{{runBenchmarkTest_Perf_Producer_console_output.stdout}}"