---
# Adds SSH key for all the hosts except the ones defined in r2_nfs_servers group
# as all these hosts
- name: Add SSH public key
  when: inventory_hostname not in groups['r2_nfs_servers']
  authorized_key:
    user: "{{ user_amq }}"
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  register: hostname_output

- name: Ensure the packages needed are installed on the Broker(s)
  when: inventory_hostname in groups['r2_brokers']
  dnf:
    name: "{{ broker_packages }}"
    state: latest
    update_cache: yes
  register: dnf_output

- name: Show the setting of hostname output for each of the host
  debug:
    var: hostname_output

- name: All done!!!
  debug:
    msg: Packages have been successfully installed...
