---

- name: Ensure the packages needed are installed on the Broker(s)
  become: yes
  become_user: root
  dnf:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  register: dnf_output

- name: Copy AMQ binary to NFS server
  copy:
    src: "{{ amq_binary_archive }}"
    dest: "{{ amq_binary_location }}"
    owner: "{{ user_amq }}"
    group: "{{ user_amq }}"
    mode: 0644
  register: cp_amq_binary_output

- name: Copy "amq" setup script
  template:
    src: install_amq.sh.j2
    dest: "{{amq_install_script}}"
    mode: 0755
  register: copy_amq_setup_output

- name: Copy amq setup output
  when: copy_amq_setup_output.changed is true
  debug:
    msg: "AMQ setup script copied..."

- name: Execute the "amq" setup script
  when: copy_amq_setup_output.changed is true
  shell:
    "{{ amq_install_script }}"
  register: amq_install_script_output

- name: Execute amq setup output
  when: amq_install_script_output.changed is true
  debug:
    msg:
      - "Broker installed at {{ amq_broker_dir }}/{{ broker_name }}."
      - "*** Setup script might have created backup directories for AMQ and broker ***"

- name: Copy amq config files - broker/jgroup/bootstrap
  template:
    src: "{{ item }}.j2"    # iterate over all the template files specified in the loop
    dest: "{{ amq_config_dir }}/{{ item }}"
    mode: 0644
  loop:
    - bootstrap.xml
  register: copy_amq_config_output

- name: Copy amq config files output
  when: copy_amq_config_output.changed is true
  debug:
    msg: "AMQ config files copied to {{ amq_config_dir }} ..."

- name: All done!!!
  when: (copy_amq_setup_output.changed is true) or (amq_install_script_output.changed is true) or (copy_amq_jgroups_output.changed is true)
  debug:
    msg: "Broker custom setup complete..."








- name: Show the dnf output
  when: dnf_output.changed is true
  debug:
    msg: "Broker packages {{ packages }} installed successfully..."









- name: All done!!!
  when: dnf_output.changed is true
  debug:
    msg: "Standalone Broker setup complete..."