---

- name: Copy "amq" broker run script
  template:
    src: run_broker.sh.j2
    dest: "{{amq_broker_run_script}}"
    mode: 0755
  register: copy_run_broker_script_output

- name: Copy "amq" broker run script - output
  when: copy_run_broker_script_output.changed is true
  debug:
    msg:
      - "AMQ {{ broker_name }} run script copied..."
      - "Mirroring enabled: {{ enable_amq_mirroring }}"

- name: Execute the "amq" broker run script
  shell:
    "{{amq_broker_run_script}}"
  register: amq_broker_run_script_output

- name: Execute the "amq" broker run script - output
  when: amq_broker_run_script_output.changed is true
  debug:
    var: amq_broker_run_script_output.stdout_lines
