---

- name: Install Boto3
  include_role:
    name: setup_boto

- name: Create key pair using local public key
  amazon.aws.ec2_key:
    profile: "{{ aws_profile_name }}"
    name: "{{ key_pair_name }}"
    key_material: "{{ lookup('file', pub_key_location) }}"
    region: "{{ item }}"
  with_items: "{{ aws_regions }}"
  register: ec2_key_pair_output

- name: Create key pair output
  debug:
    msg: "{{ ec2_key_pair_output.results |
             json_query('[].[item, msg]')|
             map('join', '\n') }}"

