---
- hosts: broker
  gather_facts: yes
  vars:
    AMQ_USER: amq_runner
    ansible_become: yes
    ansible_become_user: "{{AMQ_USER}}"
    ansible_become_password: redhat
    BROKER_CONFIG_DIR: '/var/opt/amq-broker/broker-01/etc/'
  tasks:
    - name: Copy broker.xml file
      ansible.builtin.copy:
        src: ./input-files/broker.xml   
        dest: "{{BROKER_CONFIG_DIR}}"
        owner: "{{AMQ_USER}}"

    - name: Copy broker-keystore.p12 file
      ansible.builtin.copy:
        src: ./input-files/broker-keystore.p12
        dest: "{{BROKER_CONFIG_DIR}}"
        owner: "{{AMQ_USER}}"