---

# Brokers in region 1 - vpc1
r1_vpc1_brokers:
  hosts:
    r1-broker01-live:
      broker_data_directory: one
      broker_name: broker-01
      broker_private_ip: 10.70.0.51
      is_live_broker: true
      mirror_primary_host_idx: 0
      mirror_backup_host_idx: 1
    r1-broker02-bak:
      broker_data_directory: one
      broker_name: broker-02
      broker_private_ip: 10.70.64.51
      mirror_primary_host_idx: 1
      mirror_backup_host_idx: 0
    r1-broker03-live:
      broker_data_directory: two
      broker_name: broker-03
      broker_private_ip: 10.70.128.51
      is_live_broker: true
      mirror_primary_host_idx: 2
      mirror_backup_host_idx: 3
    r1-broker04-bak:
      broker_data_directory: two
      broker_name: broker-04
      broker_private_ip: 10.70.0.52
      mirror_primary_host_idx: 3
      mirror_backup_host_idx: 2
  vars:
    mirror_group: r2_vpc1_brokers
    nfs_server_ip: 10.70.0.50

# Brokers in region 1 - vpc2
r1_vpc2_brokers:
  hosts:
    r1-broker05-live:
      broker_data_directory: three
      broker_name: broker-05
      broker_private_ip: 10.71.128.61
      is_live_broker: true
      mirror_primary_host_idx: 0
      mirror_backup_host_idx: 1
    r1-broker06-bak:
      broker_data_directory: three
      broker_name: broker-06
      broker_private_ip: 10.71.64.61
      mirror_primary_host_idx: 1
      mirror_backup_host_idx: 0
    r1-broker07-live:
      broker_data_directory: four
      broker_name: broker-07
      broker_private_ip: 10.71.0.61
      is_live_broker: true
      mirror_primary_host_idx: 2
      mirror_backup_host_idx: 3
    r1-broker08-bak:
      broker_data_directory: four
      broker_name: broker-08
      broker_private_ip: 10.71.128.62
      mirror_primary_host_idx: 3
      mirror_backup_host_idx: 2
  vars:
    nfs_server_ip: 10.71.64.60
    mirror_group: r2_vpc2_brokers

# Brokers in region 2 - vpc1
r2_vpc1_brokers:
  hosts:
    r2-broker01-live:
      broker_data_directory: one
      broker_name: broker-01
      broker_private_ip: 10.75.0.51
      is_live_broker: true
      mirror_primary_host_idx: 0
      mirror_backup_host_idx: 1
    r2-broker02-bak:
      broker_data_directory: one
      broker_name: broker-02
      broker_private_ip: 10.75.64.51
      mirror_primary_host_idx: 1
      mirror_backup_host_idx: 0
    r2-broker03-live:
      broker_data_directory: two
      broker_name: broker-03
      broker_private_ip: 10.75.128.51
      is_live_broker: true
      mirror_primary_host_idx: 2
      mirror_backup_host_idx: 3
    r2-broker04-bak:
      broker_data_directory: two
      broker_name: broker-04
      broker_private_ip: 10.75.0.52
      mirror_primary_host_idx: 3
      mirror_backup_host_idx: 2
  vars:
    nfs_server_ip: 10.75.0.50
    mirror_group: r1_vpc1_brokers

# Brokers in region 2 - vpc2
r2_vpc2_brokers:
  hosts:
    r2-broker05-live:
      broker_data_directory: three
      broker_name: broker-05
      broker_private_ip: 10.76.128.61
      is_live_broker: true
      mirror_primary_host_idx: 0
      mirror_backup_host_idx: 1
    r2-broker06-bak:
      broker_data_directory: three
      broker_name: broker-06
      broker_private_ip: 10.76.64.61
      mirror_primary_host_idx: 1
      mirror_backup_host_idx: 0
    r2-broker07-live:
      broker_data_directory: four
      broker_name: broker-07
      broker_private_ip: 10.76.0.61
      is_live_broker: true
      mirror_primary_host_idx: 2
      mirror_backup_host_idx: 3
    r2-broker08-bak:
      broker_data_directory: four
      broker_name: broker-08
      broker_private_ip: 10.76.128.62
      mirror_primary_host_idx: 3
      mirror_backup_host_idx: 2
  vars:
    nfs_server_ip: 10.76.64.60
    mirror_group: r1_vpc2_brokers

r1_nfs_servers:
  hosts:
    r1-vpc1-nfs-server:
      zone1_cidr: 10.70.0.0/24
      zone2_cidr: 10.70.64.0/24
      zone3_cidr: 10.70.128.0/24
    r1-vpc2-nfs-server:
      zone1_cidr: 10.71.0.0/24
      zone2_cidr: 10.71.64.0/24
      zone3_cidr: 10.71.128.0/24

r2_nfs_servers:
  hosts:
    r2-vpc1-nfs-server:
      zone1_cidr: 10.75.0.0/24
      zone2_cidr: 10.75.64.0/24
      zone3_cidr: 10.75.128.0/24
    r2-vpc2-nfs-server:
      zone1_cidr: 10.76.0.0/24
      zone2_cidr: 10.76.64.0/24
      zone3_cidr: 10.76.128.0/24

r1_routers:
  hosts:
    r1-router01-hub:
    r1-router02-spoke:
    r1-router03-spoke:

r1_routers:
  hosts:
    r1-router01-hub:
      router_id: router.hub-01
      router_private_ip: 10.75.128.100
    r1-router02-spoke:
      router_id: router.to.cluster-01
      router_private_ip: 10.75.64.100
      live_broker_01_host: live-broker-01
      live_broker_02_host: live-broker-02
    r1-router03-spoke:
      router_id: router.to.cluster-01
      router_private_ip: 10.76.0.100
      live_broker_01_host: live-broker-03
      live_broker_02_host: live-broker-04
  vars:
    router_group: r2_routers
    broker_group: r2_vpc1_brokers
    broker_01_host: amq-live-broker-01
    broker_02_host: amq-live-broker-02

r2_routers:
  hosts:
    r2-router01-hub:
      router_id: router.hub-01
      router_private_ip: 10.75.128.100
      router_config_file_prefix: hub-router
    r2-router02-spoke:
      router_id: router.to.cluster-01
      router_private_ip: 10.75.64.100
      live_broker_01_host: live-broker-01
      live_broker_02_host: live-broker-02
      broker_group: r2_vpc1_brokers
      router_config_file_prefix: spoke-router
    r2-router03-spoke:
      router_id: router.to.cluster-02
      router_private_ip: 10.76.0.100
      live_broker_01_host: live-broker-03
      live_broker_02_host: live-broker-04
      broker_group: r2_vpc2_brokers
      router_config_file_prefix: spoke-router
  vars:
    router_group: r2_routers
    live_broker_01_host_idx: 0
    live_broker_02_host_idx: 2


# Parent for all the broker groups
brokers:
  children:
    r1_vpc1_brokers:
    r1_vpc2_brokers:
    r2_vpc1_brokers:
    r2_vpc2_brokers:
  vars:
    broker_run_time_in_days: 7

nfs_servers:
  children:
    r1_nfs_servers:
    r2_nfs_servers:
  vars:
    user_nobody: "nobody"

routers:
  children:
    r1_routers:
    r2_routers:

all:
  vars:
    ansible_connection: ssh
    ansible_user: root
    user_amq: "amq_runner"
    nfs_mount_point: "/mnt/nfs_shares/amq"
    nfs_files_mount: "{{nfs_mount_point}}/files"
    nfs_server_host: "nfs-server"
    broker_mount_base_dir: "/mnt/nfs_mount"
    broker_mount_dir: "{{broker_mount_base_dir}}/amq"
    enable_amq_mirroring: true
