---

- hosts:
    - brokers
  become: 'yes'
  become_user: "{{ user_amq }}"
  become_method: sudo
  gather_facts: false
  roles:
    - run_broker
  tags: run_broker

- hosts:
    - routers
  become: 'yes'
  become_user: "{{ user_amq }}"
  become_method: sudo
  gather_facts: false
  roles:
    - run_router
  tags: run_router
