---

- hosts:
    - brokers
  become: 'yes'
  become_user: "{{ user_amq }}"
  become_method: sudo
  roles:
    - run_broker

- hosts:
    - routers
  become: 'yes'
  become_user: "{{ user_amq }}"
  become_method: sudo
  roles:
    - run_router
