---

- hosts:
    - r1-broker04-bak
  become: 'yes'
  become_method: sudo
  gather_facts: false
  roles:
    - role: setup_jmeter_client
      become: true
      become_user: "{{ user_amq }}"
      tags:
        - setup_jmeter
    - role: run_jmeter_n_messages_test
      become: true
      become_user: "{{ user_amq }}"
      tags:
        - run_jmeter_n_messages_test