---

- hosts:
    - brokers
  become: 'yes'
  become_user: "{{ user_amq }}"
  become_method: sudo
  gather_facts: false
  roles:
    - stop_broker

- hosts:
    - routers
  become: 'yes'
  become_user: "{{ user_amq }}"
  become_method: sudo
  gather_facts: false
  roles:
    - stop_router
