enable_amq_mirroring: true

### Start - SSL Variables
enable_ssl: true
ssl_generate_ca: true
ssl_generate_certs: true

CA_CERT_FILE_PREFIX: server-ca
INPUT_FILES_BASE_DIR: './generated'
CA_CERT_DIR: "{{ INPUT_FILES_BASE_DIR }}/ca-certs"
KEY_PASS: redhat
STORE_PASS: redhat
### END - SSL Variables

# Region 1 TOR Hosts & IPs
r1_broker01_live_ip:      163.66.94.75
r1_broker02_bak_ip:       163.74.85.119
r1_broker03_live_ip:      163.75.84.23
r1_broker04_bak_ip:       163.66.90.34
r1_vpc1_nfs_server_ip:    163.66.94.73
r1_router01_hub_ip:       163.75.95.11
r1_router02_spoke_ip:     163.74.81.155
r1_broker05_live_ip:      163.75.84.21
r1_broker06_bak_ip:       163.74.85.122
r1_broker07_live_ip:      163.66.87.248
r1_broker08_bak_ip:       163.75.95.14
r1_vpc2_nfs_server_ip:    163.74.92.75
r1_router03_spoke_ip:     163.66.94.74


ansible_ssh_private_key_file: ~/Documents/RED/amq_aws-key_pair-TOR.cer
ansible_user: ec2-user
cloud_provider: aws
