enable_amq_mirroring: true

### Start - SSL Variables
enable_ssl: true
ssl_generate_ca: true
ssl_generate_certs: true 

CA_CERT_FILE_PREFIX: server-ca
INPUT_FILES_BASE_DIR: './generated'
CA_CERT_DIR: "{{ INPUT_FILES_BASE_DIR }}/ca-certs"
KEY_PASS: redhat 
STORE_PASS: redhat 
### END - SSL Variables

# Region 1 TOR Hosts & IPs
r1_broker01_live_ip:      163.66.90.168
r1_broker02_bak_ip:       163.74.89.75
r1_broker03_live_ip:      163.75.89.39
r1_broker04_bak_ip:       163.66.94.233
r1_vpc1_nfs_server_ip:    163.66.84.62
r1_router01_hub_ip:       163.75.94.42
r1_router02_spoke_ip:     163.74.87.187
r1_broker05_live_ip:      163.75.86.170
r1_broker06_bak_ip:       163.74.81.236
r1_broker07_live_ip:      163.66.90.167
r1_broker08_bak_ip:       163.75.89.38
r1_vpc2_nfs_server_ip:    163.74.81.235
r1_router03_spoke_ip:     163.66.94.232

# Region 2 DAL Hosts & IPs
r2_broker01_live_ip:      150.240.65.213
r2_broker02_bak_ip:       52.116.201.178
r2_broker03_live_ip:      52.117.9.119
r2_broker04_bak_ip:       52.118.188.12
r2_vpc1_nfs_server_ip:    52.116.134.153
r2_router01_hub_ip:       169.48.92.37
r2_router02_spoke_ip:     150.239.171.188
r2_broker05_live_ip:      52.118.83.32
r2_broker06_bak_ip:       52.116.197.60
r2_broker07_live_ip:      52.118.185.30
r2_broker08_bak_ip:       52.117.9.118
r2_vpc2_nfs_server_ip:    150.239.171.212
r2_router03_spoke_ip:     150.240.66.110
