enable_amq_mirroring: true

### Start - SSL Variables
#enable_ssl: true
#ssl_generate_ca: true
#ssl_generate_certs: true
#
#CA_CERT_FILE_PREFIX: server-ca
#INPUT_FILES_BASE_DIR: './generated'
#CA_CERT_DIR: "{{ INPUT_FILES_BASE_DIR }}/ca-certs"
#KEY_PASS: redhat
#STORE_PASS: redhat
### END - SSL Variables

# Region 1 TOR Hosts & IPs
r1_broker01_live_ip:      18.118.162.114
r1_broker02_bak_ip:       18.191.182.65
r1_broker03_live_ip:      3.17.143.51
r1_broker04_bak_ip:       3.145.46.4
r1_vpc1_nfs_server_ip:    13.58.180.156
r1_router01_hub_ip:       18.222.211.159
r1_router02_spoke_ip:     3.135.207.68
r1_broker05_live_ip:      3.17.131.93
r1_broker06_bak_ip:       18.189.193.44
r1_broker07_live_ip:      18.221.89.25
r1_broker08_bak_ip:       13.59.111.87
r1_vpc2_nfs_server_ip:    3.14.7.156
r1_router03_spoke_ip:     18.224.169.162

## Variables for AWS setup. Please un-comment these when setting up on AWS
# todo(sg): update readme to add the AWS private key info
private_key_location: "~/.ssh/id_rsa"
ansible_ssh_private_key_file: "{{ private_key_location }}"
ansible_user: ec2-user
cloud_provider: aws
nfs_or_efs: nfs

aws_profile_name: terraform_redhat
efs_options: "defaults,vers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport"
resource_prefix: "tmp-sg"

# For SSH key pair
key_pair_name: amq_aws-key_pair-SG    # This name should match what's used in Terraform
pub_key_location: "{{ private_key_location }}.pub"
aws_regions:
  - us-east-2   #US East (Ohio)
  - ca-central-1

r1_vpc1_private_ip_prefix: "10.110"
r1_vpc2_private_ip_prefix: "10.111"
