---

- name: IP address
  debug:
    msg:
      - "ansible_host = {{ ansible_host }}"
#      - "ansible_address = {{ ansible_eth0.ipv4.address }}"
      - "hostname = {{ inventory_hostname }}"

- name: Stop broker
  include_role:
    name: stop_broker

- name: Reset EFS
  when: nfs_or_efs is defined and nfs_or_efs == "efs"
  include_role:
    name: reset_efs

- name: Reset NFS
  when: nfs_or_efs is not defined or nfs_or_efs == "nfs"
  include_role:
    name: reset_nfs

- name: Delete broker directories
  include_role:
    name: reset_broker_install_dir

- name: Remove broker packages
  dnf:
    name: "{{ packages }}"
    state: absent
    update_cache: yes

- name: Delete AMQ user
  ansible.builtin.user:
    name: "{{ user_amq }}"
    state: absent
    # Remove the user directories as well
    remove: yes

- name: Delete AMQ user group
  ansible.builtin.group:
    name: "{{ user_amq }}"
    state: absent

- name: All done!!!
  debug:
    msg: "Broker config removed completely..."
