locals {
  R1_VPC1_MAIN_CIDR_BLOCK = "${var.R1_VPC1_PRIVATE_IP_PREFIX}.0.0/16"
  R1_VPC2_MAIN_CIDR_BLOCK = "${var.R1_VPC2_PRIVATE_IP_PREFIX}.0.0/16"
  R2_VPC1_MAIN_CIDR_BLOCK = "${var.R2_VPC1_PRIVATE_IP_PREFIX}.0.0/16"
  R2_VPC2_MAIN_CIDR_BLOCK = "${var.R2_VPC2_PRIVATE_IP_PREFIX}.0.0/16"

  NAME_PREFIX = "${var.PREFIX}-AMQ_COB"
  R1_AMI_ID      = lookup(var.AMI, var.REGION_1)
  R2_AMI_ID      = lookup(var.AMI, var.REGION_2)

  KEY_NFS       = "nfs"
  KEY_BROKER_01 = "broker_01"
  KEY_BROKER_02 = "broker_02"
  KEY_BROKER_03 = "broker_03"
  KEY_BROKER_04 = "broker_04"
  KEY_ROUTER_01 = "router_01"
  KEY_ROUTER_02 = "router_02"
  KEY_ROUTER_03 = "router_03"

  R1_VPC1_IP_NUMBER_PREFIX = {
    "0" : "${var.R1_VPC1_PRIVATE_IP_PREFIX}.${var.SUBNET_1_3RD_OCTET}"
    "1" : "${var.R1_VPC1_PRIVATE_IP_PREFIX}.${var.SUBNET_2_3RD_OCTET}"
    "2" : "${var.R1_VPC1_PRIVATE_IP_PREFIX}.${var.SUBNET_3_3RD_OCTET}"
  }

  R1_VPC2_IP_NUMBER_PREFIX = {
    "0" : "${var.R1_VPC2_PRIVATE_IP_PREFIX}.${var.SUBNET_1_3RD_OCTET}"
    "1" : "${var.R1_VPC2_PRIVATE_IP_PREFIX}.${var.SUBNET_2_3RD_OCTET}"
    "2" : "${var.R1_VPC2_PRIVATE_IP_PREFIX}.${var.SUBNET_3_3RD_OCTET}"
  }

  R2_VPC1_IP_NUMBER_PREFIX = {
    "0" : "${var.R2_VPC1_PRIVATE_IP_PREFIX}.${var.SUBNET_1_3RD_OCTET}"
    "1" : "${var.R2_VPC1_PRIVATE_IP_PREFIX}.${var.SUBNET_2_3RD_OCTET}"
    "2" : "${var.R2_VPC1_PRIVATE_IP_PREFIX}.${var.SUBNET_3_3RD_OCTET}"
  }

  R2_VPC2_IP_NUMBER_PREFIX = {
    "0" : "${var.R2_VPC2_PRIVATE_IP_PREFIX}.${var.SUBNET_1_3RD_OCTET}"
    "1" : "${var.R2_VPC2_PRIVATE_IP_PREFIX}.${var.SUBNET_2_3RD_OCTET}"
    "2" : "${var.R2_VPC2_PRIVATE_IP_PREFIX}.${var.SUBNET_3_3RD_OCTET}"
  }
}
