---

- name: Copy router setup script
  when: cloud_provider is not defined or cloud_provider != "aws"
  template:
    src: "{{ router_install_script_basename }}.j2"
    dest: "{{ router_install_script }}"
    mode: 0755
  register: copy_router_setup_output

- name: Copy router setup script
  when: cloud_provider is defined and cloud_provider == "aws"
  template:
    src: "{{ router_install_script_basename }}.aws.j2"
    dest: "{{ router_install_script }}"
    mode: 0755
  register: copy_router_setup_output

- name: Copy router setup script output
  when: copy_router_setup_output.changed is true
  debug:
    msg: "Router setup script copied..."

- name: Execute the router setup script
  shell:
    "{{ router_install_script }}"
  register: router_install_script_output

- name: Execute router setup output
  when: router_install_script_output.changed is true
  debug:
    var: router_install_script_output.stdout_lines

- name: Add hub router and broker ip/hosts to hosts
  when: inventory_hostname.endswith('-spoke')
  blockinfile:
    path: /etc/hosts
    block: |
      {{ hub_router_ip }}    amq-{{ hub_router_id }}
      {{ first_live_broker_ip }}    amq-{{ live_broker_01_host }}
#      {{ second_live_broker_ip }}    amq-{{ live_broker_02_host }}
  register: etc_hosts_output

- name: Entries added to the /etc/hosts
  when: (inventory_hostname.endswith('-spoke')) and (etc_hosts_output.changed is true)
  debug:
    msg:
      - "{{ hub_router_ip }}  amq-{{ hub_router_id }}"
      - "{{ first_live_broker_ip }}  amq-{{ live_broker_01_host }}"
#      - "{{ second_live_broker_ip }} amq-{{ live_broker_02_host }}"

- name: Copy private key & cert files to router
  when: enable_ssl is defined and enable_ssl
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ router_config_dir }}"
    mode: 0755
  loop:
    - "{{INPUT_FILES_BASE_DIR}}/{{inventory_hostname}}/{{inventory_hostname}}-private-key.key"
    - "{{INPUT_FILES_BASE_DIR}}/{{inventory_hostname}}/{{inventory_hostname}}.crt"
    - "{{INPUT_FILES_BASE_DIR}}/ca-certs/{{CA_CERT_FILE_PREFIX}}.crt"

- name: Copy router config file
  template:
    src: "{{ router_config_file_prefix }}-config.conf.j2"
    dest: "{{ router_config_dir }}/qdrouterd.conf"
    mode: 0644
  register: copy_router_config_output

- name: All done!!!
  when: >
      (etc_hosts_output.changed is true) or (copy_router_config_output.changed is true) or
      (copy_router_config_output.changed is true)
  debug:
    msg: "Router common setup complete..."
