---

# Brokers in region 1 - vpc1
r1_vpc1_brokers:
  hosts:
    r1-broker01-live:
      broker_data_directory: one
      broker_name: broker-01
      broker_private_ip: "{{ r1_vpc1_private_ip_prefix }}.0.51"
      is_live_broker: true
      mirror_primary_host_idx: 0
      mirror_backup_host_idx: 1
      ansible_host: "{{ r1_broker01_live_ip }}"
    r1-broker02-bak:
      broker_data_directory: one
      broker_name: broker-02
      broker_private_ip: "{{ r1_vpc1_private_ip_prefix }}.64.51"
      mirror_primary_host_idx: 1
      mirror_backup_host_idx: 0
      ansible_host: "{{ r1_broker02_bak_ip }}"
  vars:
    nfs_server_ip: "{{ r1_vpc1_private_ip_prefix }}.0.50"
    mirror_group: r1_vpc2_brokers
    cluster_idx: 1


# Brokers in region 1 - vpc2
r1_vpc2_brokers:
  hosts:
    r1-broker05-live:
      broker_data_directory: three
      broker_name: broker-05
      broker_private_ip: "{{ r1_vpc2_private_ip_prefix }}.64.61"
      is_live_broker: true
      mirror_primary_host_idx: 0
      mirror_backup_host_idx: 1
      ansible_host: "{{ r1_broker05_live_ip }}"
    r1-broker06-bak:
      broker_data_directory: three
      broker_name: broker-06
      broker_private_ip: "{{ r1_vpc2_private_ip_prefix }}.0.61"
      mirror_primary_host_idx: 1
      mirror_backup_host_idx: 0
      ansible_host: "{{ r1_broker06_bak_ip }}"
  vars:
    nfs_server_ip: "{{ r1_vpc2_private_ip_prefix }}.64.60"
    mirror_group: r1_vpc1_brokers
    cluster_idx: 2


r1_nfs_servers:
  hosts:
    r1-vpc1-nfs-server:
      zone1_cidr: "{{ r1_vpc1_private_ip_prefix }}.0.0/24"
      zone2_cidr: "{{ r1_vpc1_private_ip_prefix }}.64.0/24"
      zone3_cidr: "{{ r1_vpc1_private_ip_prefix }}.128.0/24"
      ansible_host: "{{ r1_vpc1_nfs_server_ip }}"
    r1-vpc2-nfs-server:
      zone1_cidr: "{{ r1_vpc2_private_ip_prefix }}.0.0/24"
      zone2_cidr: "{{ r1_vpc2_private_ip_prefix }}.64.0/24"
      zone3_cidr: "{{ r1_vpc2_private_ip_prefix }}.128.0/24"
      ansible_host: "{{ r1_vpc2_nfs_server_ip }}"


r1_routers:
  hosts:
    r1-router01-hub:
      router_id: router.hub-01
      router_private_ip: "{{ r1_vpc1_private_ip_prefix }}.64.100"
      router_config_file_prefix: hub-router
      ansible_host: "{{ r1_router01_hub_ip }}"
    r1-router02-spoke:
      router_id: router.to.cluster-01
      router_private_ip: "{{ r1_vpc1_private_ip_prefix }}.0.101"
      live_broker_01_host: live-broker-01
      live_broker_02_host: live-broker-02
      broker_group: r1_vpc1_brokers
      router_config_file_prefix: spoke-router
      ansible_host: "{{ r1_router02_spoke_ip }}"
  vars:
    router_group: r1_routers
    live_broker_01_host_idx: 0
    live_broker_02_host_idx: 2


# Parent for all the broker groups
brokers:
  children:
    r1_vpc1_brokers:
    r1_vpc2_brokers:
  vars:
    packages:
      - nfs-utils
      - java-11-openjdk
      - zip
      - unzip

nfs_servers:
  children:
    r1_nfs_servers:
    r2_nfs_servers:
  vars:
    user_nobody: "nobody"
    nfs_service: "nfs-server.service"
    packages:
      - nfs-utils

routers:
  children:
    r1_routers:
  vars:
    packages:
      - qpid-dispatch-router
      - qpid-dispatch-tools
      - qpid-dispatch-console

all:
  vars:
    ansible_connection: ssh
    ansible_user: root
    user_amq: "amq_runner"
    nfs_mount_point: "/mnt/nfs_shares/amq"
    nfs_files_mount: "{{nfs_mount_point}}/files"
    nfs_server_host: "nfs-server"
    broker_mount_base_dir: "/mnt/nfs_mount"
    broker_mount_dir: "{{ broker_mount_base_dir }}/amq"
    broker_files_mount_dir: "{{ broker_mount_dir }}/files"
    amq_binary_location: "{{ broker_files_mount_dir }}"
    amq_advanced_topology_dir: "{{ broker_mount_dir }}/advanced_topology"
    enable_amq_mirroring: true
    amq_binary_version: amq-broker-7.9.0
    amq_binary_archive: "{{ amq_binary_version }}-bin.zip"

    nfs_or_efs: nfs

    # whether to delete AMQ binary when resetting the NFS server
    delete_amq_archive: false

    # Jmeter client setup playbook variables.
    jmeter_hub_router_ip: "{{ r1_vpc1_private_ip_prefix }}.64.100"
    jmeter_hub_router_port: 5672
    jmeter_binary_download_uri: https://dlcdn.apache.org/jmeter/binaries
    jmeter_binary_version: apache-jmeter-5.4.3
    jmeter_binary_archive: "{{ jmeter_binary_version }}.zip"
    jmeter_remote_bin_dir: jmeter
    clean_jmeter_home_directory: true

    resource_prefix: "cob-test"
    # for these servers we need to copy the AMQ binary as the other live/backups can simply use the mount point
    # to use the binary
    amq_binary_dest_list:
      - r1-broker01-live
      - r1-broker05-live
    amq_live_hosts: "{{ amq_binary_dest_list }}"

    # Private IP prefixes for each region/vpc
    r1_vpc1_private_ip_prefix: "10.100"
    r1_vpc2_private_ip_prefix: "10.101"
