---
- name: Install jmeter client packages.
  become: yes
  become_user: root
  ansible.builtin.package:
    name: "{{ jmeter_packages }}"
    state: present

- name: Delete jmeter client home directory
  file:
    state: absent
    path: "{{ jmeter_remote_bin_dir_full_path }}"
    mode: 0744
  when: (clean_jmeter_home_directory is defined and clean_jmeter_home_directory == true)

- name: Prepare JMeter client directories
  ansible.builtin.file:
    path: "{{ jmeter_remote_bin_dir_full_path }}"
    state: directory

- name: "Download jmeter binary {{ jmeter_binary_archive }}"
  get_url:
    url: "{{ jmeter_binary_download_uri }}/{{ jmeter_binary_archive }}"
    dest: "{{ jmeter_remote_bin_dir_full_path }}/{{ jmeter_binary_archive }}"
    mode: '0644'

- name: "unzip jmeter archive to {{ jmeter_remote_bin_dir_full_path }}/{{ jmeter_binary_version }}"
  ansible.builtin.unarchive:
    src: "{{ jmeter_remote_bin_dir_full_path }}/{{ jmeter_binary_archive }}"
    dest: "{{ jmeter_remote_bin_dir_full_path }}"
    remote_src: yes

- name: "Download qpid-amqp-1-0-client jars to the jmeter lib/ext directory."
  get_url:
    url: "https://repo1.maven.org/maven2/org/apache/qpid/{{item}}/{{jmeter_ext_jar_qpid_version}}/{{item}}-{{jmeter_ext_jar_qpid_version}}.jar"
    dest: "{{ jmeter_remote_bin_dir_full_path }}/{{ jmeter_binary_version }}/lib/ext"
    mode: '0644'
  loop:
    - "{{ jmeter_ext_jar_qpid_jms_artifact_id }}"
    - "{{ jmeter_ext_jar_qpid_client_artifact_id }}"
    - "{{ jmeter_ext_jar_qpid_common_artifact_id }}"

- name: "copy the jmeter JMX files and gen_throughput.sh file."
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ jmeter_remote_bin_dir_full_path }}/{{ item }}"
    mode: 0744
  loop:
    - AMQ_Jmeter_Test_Plan_N_Messages.jmx
    - AMQ_Jmeter_Test_Plan_N_Messages_Consumer.jmx
    - AMQ_Jmeter_Test_Plan_N_Messages_Producer.jmx
    - AMQ_Jmeter_Test_Plan_Perf.jmx
    - AMQ_Jmeter_Test_Plan_Perf_Consumer.jmx
    - AMQ_Jmeter_Test_Plan_Perf_Producer.jmx
    - gen_throughput.sh

#- name: "Copy all dependent shell script template files to {{ jmeter_remote_bin_dir_full_path }} "
#  template: src={{item.src}} dest="{{ jmeter_remote_bin_dir_full_path }}/{{item.dest}}" mode=0744
#    src: "{{ item }}"
#    dest: "{{ jmeter_remote_bin_dir_full_path }}/{{ item | basename | regex_replace('\.j2$', '') }}"
#    mode: 0744
#  loop:
#    - runBenchmarkTest_N_Messages.sh.j2
#    - runBenchmarkTest_N_Messages_Consumer.sh.j2
#    - runBenchmarkTest_N_Messages_Producer.sh.j2
#    - runBenchmarkTest_Perf.sh.j2
#    - runBenchmarkTest_Perf_Consumer.sh.j2
#    - runBenchmarkTest_Perf_Producer.sh.j2

- name: "Copy all dependent shell script template files and jndi.properties to {{ jmeter_remote_bin_dir_full_path }} "
  template: src={{item.src}} dest={{item.dest}} mode=0744
#    src: "{{ item }}"
#    dest: "{{ jmeter_remote_bin_dir_full_path }}/{{ item | basename | regex_replace('\.j2$', '') }}"
#    mode: 0744
  with_items:
    - { src: 'runBenchmarkTest_N_Messages.sh.j2', dest: '{{ jmeter_remote_bin_dir_full_path }}/runBenchmarkTest_N_Messages.sh' }
    - { src: 'runBenchmarkTest_N_Messages_Consumer.sh.j2', dest: '{{ jmeter_remote_bin_dir_full_path }}/runBenchmarkTest_N_Messages_Consumer.sh' }
    - { src: 'runBenchmarkTest_N_Messages_Producer.sh.j2', dest: '{{ jmeter_remote_bin_dir_full_path }}/runBenchmarkTest_N_Messages_Producer.sh' }
    - { src: 'runBenchmarkTest_Perf.sh.j2', dest: '{{ jmeter_remote_bin_dir_full_path }}/runBenchmarkTest_Perf.sh' }
    - { src: 'runBenchmarkTest_Perf_Consumer.sh.j2', dest: '{{ jmeter_remote_bin_dir_full_path }}/runBenchmarkTest_Perf_Consumer.sh' }
    - { src: 'runBenchmarkTest_Perf_Producer.sh.j2', dest: '{{ jmeter_remote_bin_dir_full_path }}/runBenchmarkTest_Perf_Producer.sh' }
    - { src: 'jndi.properties.j2', dest: '/tmp/jndi.properties' }

#    - { src: 'templates/bar.j2', dest: '/etc/splat/bar.conf' }
#    - runBenchmarkTest_N_Messages.sh.j2
#    - runBenchmarkTest_N_Messages_Consumer.sh.j2
#    - runBenchmarkTest_N_Messages_Producer.sh.j2
#    - runBenchmarkTest_Perf.sh.j2
#    - runBenchmarkTest_Perf_Consumer.sh.j2
#    - runBenchmarkTest_Perf_Producer.sh.j2


#- name: Copy jmeter jndi.properties config file.
#  template:
#    src: "jndi.properties.j2"
#    dest: "/tmp/jndi.properties"
#    mode: 0644
#  register: copy_jmeter_jndi_config_output

#- name: Upload runBenchmarkTest_N_Messages.sh script.
#  template:
#    src: "runBenchmarkTest_N_Messages.sh.j2"
#    dest: "{{ jmeter_remote_bin_dir_full_path }}/runBenchmarkTest_N_Messages.sh"
#    mode: 0744
#  register: copy_runBenchmarkTest_N_Messages
#
#- name: Upload runBenchmarkTest_Perf.sh script.
#  template:
#    src: "runBenchmarkTest_Perf.sh.j2"
#    dest: "{{ jmeter_remote_bin_dir_full_path }}/runBenchmarkTest_Perf.sh"
#    mode: 0744
#  register: copy_runBenchmarkTest_Perf