---

- name: Copy "amq" router run script
  template:
    src: run_router.sh.j2
    dest: "{{amq_router_run_script}}"
    mode: 0755
  register: copy_run_router_script_output

- name: Copy "amq" router run script - output
  when: copy_run_router_script_output.changed is true
  debug:
    msg: "AMQ {{ router_id }} run script copied..."

- name: Execute the "amq" router run script
  shell:
    "{{ amq_router_run_script }}"
  register: amq_router_run_script_output

- name: Run AMQ router instance - result - 2
  when: amq_router_run_script_output.changed is true
  debug:
    var: amq_router_run_script_output.stdout_lines
