---
- hosts:
    - brokers
  become: 'yes'
  become_method: sudo
  gather_facts: false
  roles:
    - role: setup_common
      tags:
        - setup_broker
        - setup_common
    - role: setup_hostname
      tags:
        - setup_broker
        - setup_broker_hostname
    # Add "amq_user" to sudoers to allow invoking "sudo" without password prompt
    - role: setup_broker-sudoer-add
      tags:
        - setup_broker
        - setup_broker_sudoer_add
    - role: setup_broker-standalone
      become: true
      become_user: "{{ user_amq }}"
      tags:
        - setup_broker
        - update_broker_config
    # Remove "amq_user" from sudoers so that password prompt is shown when invoking "sudo"
    - role: setup_broker-sudoer-remove
      tags:
        - setup_broker
        - setup_broker_sudoer_remove


- hosts:
    - routers
  become: 'yes'
  become_method: sudo
  gather_facts: false
  roles:
    - role: setup_common
      tags:
        - setup_router
        - setup_router_common
    - role: setup_hostname
      tags:
        - setup_router
        - setup_router_hostname
    - role: setup_router
      tags:
        - setup_router
        - register_router
      force_handlers: True
