---
# This playbook
# 1) setups jmeter client
# 2) runs the jmeter test on multiple hosts combines the results - the producer which produces specified number of messages and consumes unlimited number of messages.
- hosts:
    - r1-broker02-bak
    - r1-broker04-bak
  become: 'yes'
  become_method: sudo
  gather_facts: false
  roles:
    - role: setup_jmeter_client
      become: true
      become_user: "{{ user_amq }}"
      tags:
        - setup_jmeter
    - role: run_jmeter_parallel_perf_test
      become: true
      become_user: "{{ user_amq }}"
      tags:
        - run_jmeter_parallel_perf_test