---

- include_role:
    name: unmount_nfs

- name: Remove NFS server from hosts
  blockinfile:
    path: /etc/hosts
    state: absent

- name: Remove AMQ broker and install directory recursively
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ amq_broker_dir }}"
    - "{{ amq_install_dir }}"
    - "{{ amq_advanced_topology_dir }}"
