---

- name: IP address
  debug:
    msg:
      - "ansible_host = {{ ansible_host }}"
      - "hostname = {{ inventory_hostname }}"

- name: Stop broker
  include_role:
    name: stop_broker

- name: Delete broker directories
  include_role:
    name: reset_broker_install_dir

- name: Remove broker packages
  dnf:
    name: "{{ packages }}"
    state: absent
    update_cache: yes

- name: Delete AMQ user
  ansible.builtin.user:
    name: "{{ user_amq }}"
    state: absent
    # Remove the user directories as well
    remove: yes

- name: Delete AMQ user group
  ansible.builtin.group:
    name: "{{ user_amq }}"
    state: absent

- name: All done!!!
  debug:
    msg: "Broker config removed completely..."
