---

- name: Ensure the packages needed are installed on the Broker(s)
  dnf:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  register: dnf_output

- name: Unmount existing mount point (if any)
  include_role:
    name: unmount_nfs

- name: Mount NFS
  when: nfs_or_efs is not defined or nfs_or_efs == "nfs"
  include_role:
    name: mount_nfs

- name: Mount EFS
  when: nfs_or_efs is defined and nfs_or_efs == "efs"
  include_role:
    name: mount_efs

- name: Show the dnf output
  when: dnf_output.changed is true
  debug:
    msg: "Broker packages {{ packages }} installed successfully..."

- name: All done!!!
  when: (dnf_output.changed is true) or (create_mount_dir_output.changed is true) or (mount_nfs_output.changed is true) or (etc_hosts_output.changed is true)
  debug:
    msg: "Broker common setup complete..."